apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentserver
  template:
    metadata:
      labels:
        app: studentserver
    spec:
      containers:
      - name: studentserver
        image: zhou19539/studentserver
        envFrom:
        - configMapRef:
            name: studentserver-config
        ports:
        - containerPort: 8080